server:
  port: 8080
  servelet:
    context-path: /bootcamp

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: postgres://xguqurocfuakmv:56212d3a359001065d59aa6483b9ff870628bc26bacd27a760aa80c47989dcf0@ec2-34-232-191-133.compute-1.amazonaws.com:5432/dcvdm6qmjl9nvm
    username: xguqurocfuakmv
    password: 56212d3a359001065d59aa6483b9ff870628bc26bacd27a760aa80c47989dcf0
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    hibernate:
      ddl-auto: none

application:
  description: Projeto criado para o bootcamp DIO - Santander